# **Arrays Vs Lists**

In [0]:
import numpy as np

In [0]:
L = [1,2,3]

In [0]:
A = np.array([1,2,3])

In [0]:
for e in L:
  print(e)

1
2
3


In [0]:
for e in A:
  print(e)

1
2
3


In [0]:
L.append(4)
L

[1, 2, 3, 4]

In [0]:

#append does not work in numpy
A.append(4)


In [0]:
#adding arrays together
L + [5]

[1, 2, 3, 4, 5]

In [0]:
A + np.array([4])
#but this will add four to each value , called broadcasting , instead of adding the value 4 into the array

In [0]:
A + np.array([4,5,6])
#this will add 4 to 1, 5 to 2, 6 to 3

In [0]:
 #will multiple all the elements inside the array
 2 * A


In [0]:
#however multiplying the list will just add into it  (reputition) 
2 * L

#so does L + L 


In [0]:
#in order to add a 3 to each element in L we need to do this 

L2 = []
for e in L:
  L2.append(e + 3)

L2 



In [0]:
#another way of doing it will be to do
L2 = [e + 3 for e in L]
L2

In [0]:
#this is to get the square of each number in the array
L2 = []
for e in L:
  L2.append(e ** 2)

In [0]:
#this can be done easier using numpy
A**2


In [0]:
#numpy has an easy function to square root each element in the array
np.sqrt(A)

In [0]:
#or even get the log of A
np.log(A)

In [0]:
#and get the exponential 
np.exp(A)

In [0]:
# A common function in machine learning and deep learning is the hyperbolic tangent 
np.tanh(A)

In [0]:
#There are many more functions but this is some of the basics but can be used further for other functions

# **The Dot Product**

In [0]:
#one dimensional arrays

a = np.array([1,2])
b = np.array([3,4])



In [4]:
#multiple the two element arrays together 

dot = 0
for e,f in zip(a,b):
  dot += e * f

dot

11

In [0]:
dot = 0
for i in range(len(a)):
  dot += a[i] * b[i]
dot

In [0]:
#this give element wise multiplication similar to above but not adding them togther
a * b

In [5]:
#this gives the sum though of a + b 
np.sum(a * b)

#this gives the same by using this though 
(a * b).sum()

11

In [6]:
#another way can be as simple as though using 

np.dot(a,b)

#or even using this gives the same answer
a.dot(b)

11

In [0]:
#in newer versions of numpy it can be as simple to do this by using just the @ symbol
a @ b

In [0]:
#maginute of the vector is :
amag = np.sqrt((a * a).sum())
amag

In [0]:
#linear algebra tools 

np.linalg.norm(a)


In [7]:
#now that we know the above we can work out the cosine of the angle
cosangle = a.dot(b) /(np.linalg.norm(a)* np.linalg.norm(b))

cosangle

0.9838699100999074

In [8]:
#if we want the actual angle then we use arccros
angle = np.arccos(cosangle)
angle

0.17985349979247847

# **Matrices**

In [9]:
# 2 dimenstional arrays as matrices , this demo is the basics 

#this is a two by two matrix 
L = [[1,2],[3,4]]
L

[[1, 2], [3, 4]]

In [10]:
#array access :

L[0]

L[0][1]

2

In [11]:
A = np.array([[1,2],[3,4]])
A


array([[1, 2],
       [3, 4]])

In [12]:
#to get a colomn of the matrix 

A[:,0]

array([1, 3])

In [0]:
#to use an exponential

np.exp(A)

In [0]:
#numpy will take a list and make it look like an array such as 
np.exp(L)

In [0]:
#a fundamental matrix function is multiplication

B = np.array([[1,2,3],[4,5,6]])
B



In [0]:
# a star does element multiplication but without a star does matrix multiplicationn 
A.dot(B)

# **Solving Linear Systems:**

Example

Admin fee is 1.50 for children and 4.00 for adults , on a certain day there was 2200 people and it collected 5050 worth of money.

How many children and how many adults were there?

2 Equations 
2 Unknonws 

x1 + x2 = 2200
1.5x1 + 4x1 = 5050

In [0]:
# we can convert this into a matrix 

#so A = (1,1),(1.5,4) and B = (2200),(5050)

In [0]:
A = np.array([[1,1],[1.5,4]])
B = np.array([2200,5050])

In [14]:
np.linalg.solve(A,B)


array([1500.,  700.])

In [0]:
#therefore there are 1500 adults and 500 children

# **Generating Data**

This will be looking at generating hundreds or thousands of arrays of matrices 

This can be done with nerual networks

In [0]:
#array of all 0's 

np.zeros((2,3))


In [0]:
#to get 10 instead of 0s we can use

10 * np.ones((2,3))

In [0]:
#to get random number 
np.random.random()

In [15]:
#to get a random number array of 2 by 3 array

np.random.random((2,3))

array([[0.05109738, 0.06032997, 0.71073415],
       [0.82233874, 0.85963115, 0.48152325]])

In [16]:
#to get random postive and negative numbers then use 

np.random.randn(2,3)


array([[-0.40036695,  0.63752188,  0.85965118],
       [-0.3449342 , -1.47323924,  0.97684812]])

In [21]:
#to get the mean of the array would be 

R = np.random.randn(10000)

R.mean()

#or could be used as 
np.mean(R)

0.013513244251971077

In [22]:
#Calculate the variance

R.var()


1.0067814752493387

In [23]:
#To get the standard deviation

R.std()

1.0033850084834528

In [0]:
#To get the mean of 10000 by 3 array then use the following
R = np.random.randn(10000,3)

#this will get the mean for the of each column , by changing the axis to 1 will change the result
R.mean(axis = 0)


In [24]:
#to get a custom array of random numbers between 0 and 10 and make it 3 by 3 then it would be

np.random.randint(0,10, size=(3,3))


array([[0, 2, 1],
       [8, 3, 3],
       [3, 4, 4]])